function f = f_fil_3D(S,P)
% calculate the force generated by the polymerization of actin barbed ends
    f = zeros(size(S,1),3);
    if ~isempty(P.a_points)
        B =P.alpha;
        for l=1:size(P.a_points,1)
            aux_dist = sqrt((S(:,1)-P.a_points(l,1)).^2 + (S(:,2)-P.a_points(l,2)).^2 + (S(:,3)-P.a_points(l,3)).^2);
            aux_dir = [S(:,1)-P.a_points(l,1) S(:,2)-P.a_points(l,2) S(:,3)-P.a_points(l,3)];
            f =f +  B*(aux_dir./(aux_dist.^2));
        end
    end
end